name: splitwise_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Animations
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.66.0

  # State Management
  provider: ^6.1.1

  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
